TIMEOUT 1
DEFAULT main
MENU TITLE Boot menu

label main
	kernel /boot/Image
	fdt /boot/rk3588-inmys-smarc-tester.dtb
	#fdtdir /boot/
	append earlycon=uart8250,mmio32,0xfeb50000 console=ttyS2,1500000 root=PARTUUID=31474154-01 rootwait pcie_aspm=off csitpg.force_nlines=2
	#append earlycon=uart8250,mmio32,0xfeb50000 console=ttyS2,1500000 root=/dev/mmcblk1p1 rootwait pcie_aspm=off csitpg.force_nlines=2

#pcie_aspm=off for intel 7265 wifi
#csitpg.force_nlines=2 for csi_tester+nms-sm-rk3588: CSI0 on SMARC connector only x2 (CSI1: x4)

label fallback
	kernel /boot/Image.ok
	fdt /boot/rk3588-inmys-smarc-tester.dtb.ok
	append earlycon=uart8250,mmio32,0xfeb50000 console=ttyS2,1500000 root=PARTUUID=31474154-01 rootwait pcie_aspm=off csitpg.force_nlines=2
	#append earlycon=uart8250,mmio32,0xfeb50000 console=ttyS2,1500000 root=/dev/mmcblk1p1 rootwait pcie_aspm=off csitpg.force_nlines=2
