#!/bin/sh

#resize fs
size=`df -h | grep /dev/root | awk '{print $2}'`
if [ "${size::-1}" -lt "800" ]; then
	resize2fs /dev/mmcblk2p1
	resize2fs /dev/mmcblk2p2
	resize2fs /dev/mmcblk2p3
fi

# for debug
mount -t debugfs debugfs /sys/kernel/debug

if [ -e /dev/mmcblk1p3 ]; then
	# mount sdcard partition 3 to /opt
	mount /dev/mmcblk1p3 /opt
else
	# mount emmc partition 3 to /opt
	mount /dev/mmcblk2p3 /opt
fi

if [ -e /opt/postup.sh ]; then
	. /opt/postup.sh
fi

#disable rfkill
echo 1 > /sys/class/bluetooth/hci0/rfkill0/state
hciconfig hci0 up &

