#!/bin/sh

# for debug
mount -t debugfs debugfs /sys/kernel/debug

# mount partition3 (mmcblk0p3,mcblk1p3,sda3...) from boot media
# 31474154 is "TAG1" in MBR
mount PARTUUID=31474154-03 /opt/

if [ -e /opt/postup.sh ]; then
	. /opt/postup.sh
fi

